# Generated by Django 5.2.4 on 2026-02-13 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('bank', 'Bank'), ('corporate', 'Corporate'), ('auditor', 'Auditor'), ('admin', 'Admin')], max_length=20),
        ),
    ]
