# Generated by Django 5.2.4 on 2026-02-13 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(blank=True, choices=[('bank', 'Bank'), ('corporate', 'Corporate'), ('auditor', 'Auditor'), ('admin', 'Admin')], max_length=20, null=True),
        ),
    ]
