# Generated by Django 5.2.4 on 2026-02-14 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_is_approved_alter_profile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='corporate_type',
            field=models.CharField(blank=True, choices=[('buyer', 'Buyer'), ('seller', 'Seller')], max_length=10, null=True),
        ),
    ]
