# Generated by Django 6.0.1 on 2026-01-17 14:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('LOC', 'Letter of Credit'), ('INVOICE', 'Invoice'), ('BILL_OF_LADING', 'Bill of Lading'), ('PO', 'Purchase Order'), ('COO', 'Certificate of Origin'), ('INSURANCE_CERT', 'Insurance Certificate')], max_length=50)),
                ('doc_number', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='documents/')),
                ('hash', models.CharField(max_length=64)),
                ('issued_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
