# Project: Trade Finance Blockchain Explorer | Developer: Abdul Samad | FRS Standard Compliance
"""add_missing_ledger_actions

Revision ID: 007_add_missing_ledger_actions
Revises: 006_add_user_code
Create Date: 2026-02-12 18:45:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '007_add_missing_ledger_actions'
down_revision = '006_add_user_code'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add missing enum values to ledger_action
    op.execute("ALTER TYPE ledger_action ADD VALUE 'DOCUMENT_UNLINKED_FROM_TRADE'")
    op.execute("ALTER TYPE ledger_action ADD VALUE 'TRADE_UPDATED'")
    op.execute("ALTER TYPE ledger_action ADD VALUE 'TRADE_DELETED'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove enum values (not easily reversible in PostgreSQL)
    pass
    # ### end Alembic commands ###
