# Project: Trade Finance Blockchain Explorer | Developer: Abdul Samad | FRS Standard Compliance
"""Add is_active field to users table for admin approval

Revision ID: 008_add_user_approval
Revises: 007_add_missing_ledger_actions
Create Date: 2026-02-13 20:39:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '008_add_user_approval'
down_revision = '007_add_missing_ledger_actions'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Add the column with default False for new users
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=False, server_default='false'))
    
    # Set existing users to active (they were already approved before this feature)
    op.execute("UPDATE users SET is_active = true WHERE is_active = false")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_active')
    # ### end Alembic commands ###
