"""Add admin ledger actions for login/logout tracking

Revision ID: 009_add_admin_ledger_actions
Revises: 008_add_user_approval
Create Date: 2026-02-13 20:45:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '009_add_admin_ledger_actions'
down_revision = '008_add_user_approval'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # No schema changes needed - just adding new enum values
    # PostgreSQL will automatically handle the new enum values
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
