"""Add Organization model

Revision ID: 48f32a852404
Revises: 010_add_missing_enums
Create Date: 2026-02-13 21:56:38.153262

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '48f32a852404'
down_revision = '010_add_missing_enums'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'SUSPENDED', 'PENDING', name='organizationstatus'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_id'), 'organizations', ['id'], unique=False)
    op.create_index(op.f('ix_organizations_org_name'), 'organizations', ['org_name'], unique=True)
    op.drop_index('ix_audit_admin_id', table_name='audit_logs')
    op.drop_index('ix_audit_timestamp', table_name='audit_logs')
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    # Skip altering documents.doc_type - enum type issue
    op.drop_index('ix_documents_created_at', table_name='documents')
    op.drop_index('ix_documents_doc_type', table_name='documents')
    op.drop_index('ix_documents_owner_id', table_name='documents')
    op.create_index(op.f('ix_documents_id'), 'documents', ['id'], unique=False)
    # Skip altering ledger_entries.action - enum type issue
    op.drop_index('ix_ledger_created_at', table_name='ledger_entries')
    op.drop_index('ix_ledger_document_id', table_name='ledger_entries')
    op.drop_index('ix_ledger_entries_entry_hash', table_name='ledger_entries')
    op.create_index(op.f('ix_ledger_entries_id'), 'ledger_entries', ['id'], unique=False)
    op.create_unique_constraint(None, 'ledger_entries', ['entry_hash'])
    op.drop_index('ix_risk_score', table_name='risk_scores')
    op.create_index(op.f('ix_risk_scores_id'), 'risk_scores', ['id'], unique=False)
    op.drop_index('ix_trade_documents_document_id', table_name='trade_documents')
    op.drop_index('ix_trade_documents_trade_id', table_name='trade_documents')
    # Skip altering trade_transactions.status - enum type issue
    op.drop_index('ix_trades_buyer_id', table_name='trade_transactions')
    op.drop_index('ix_trades_seller_id', table_name='trade_transactions')
    op.drop_index('ix_trades_status', table_name='trade_transactions')
    op.create_index(op.f('ix_trade_transactions_id'), 'trade_transactions', ['id'], unique=False)
    # Skip altering users.role - enum type issue
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    # Skip restoring users.role alter
    op.drop_index(op.f('ix_trade_transactions_id'), table_name='trade_transactions')
    op.create_index('ix_trades_status', 'trade_transactions', ['status'], unique=False)
    op.create_index('ix_trades_seller_id', 'trade_transactions', ['seller_id'], unique=False)
    op.create_index('ix_trades_buyer_id', 'trade_transactions', ['buyer_id'], unique=False)
    # Skip restoring trade_transactions.status alter
    op.create_index('ix_trade_documents_trade_id', 'trade_documents', ['trade_id'], unique=False)
    op.create_index('ix_trade_documents_document_id', 'trade_documents', ['document_id'], unique=False)
    op.drop_index(op.f('ix_risk_scores_id'), table_name='risk_scores')
    op.create_index('ix_risk_score', 'risk_scores', ['score'], unique=False)
    op.drop_constraint(None, 'ledger_entries', type_='unique')
    op.drop_index(op.f('ix_ledger_entries_id'), table_name='ledger_entries')
    op.create_index('ix_ledger_entries_entry_hash', 'ledger_entries', ['entry_hash'], unique=True)
    op.create_index('ix_ledger_document_id', 'ledger_entries', ['document_id'], unique=False)
    op.create_index('ix_ledger_created_at', 'ledger_entries', ['created_at'], unique=False)
    # Skip restoring ledger_entries.action alter
    op.drop_index(op.f('ix_documents_id'), table_name='documents')
    op.create_index('ix_documents_owner_id', 'documents', ['owner_id'], unique=False)
    op.create_index('ix_documents_doc_type', 'documents', ['doc_type'], unique=False)
    op.create_index('ix_documents_created_at', 'documents', ['created_at'], unique=False)
    # Skip restoring documents.doc_type alter
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.create_index('ix_audit_timestamp', 'audit_logs', ['timestamp'], unique=False)
    op.create_index('ix_audit_admin_id', 'audit_logs', ['admin_id'], unique=False)
    op.drop_index(op.f('ix_organizations_org_name'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_id'), table_name='organizations')
    op.drop_table('organizations')
    # ### end Alembic commands ###
